// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	banner: Banner,
	hero: Hero,
	rich_text: RichText
};
