// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Banner from './Banner/index.svelte';
import Bento from './Bento/index.svelte';
import Detail from './Detail/index.svelte';
import Hero from './Hero/index.svelte';
import Newsletter from './Newsletter/index.svelte';
import Policies from './Policies/index.svelte';
import Productfloor from './Productfloor/index.svelte';
import Reviews from './Reviews/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	about: About,
	banner: Banner,
	bento: Bento,
	detail: Detail,
	hero: Hero,
	newsletter: Newsletter,
	policies: Policies,
	productfloor: Productfloor,
	reviews: Reviews,
	rich_text: RichText
};
