// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Catalog → Categories*
 */
export interface CatalogDocumentDataCategoriesItem {
	/**
	 * Category field in *Catalog → Categories*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.categories[].category
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	category: prismic.SelectField<'human hair' | 'synthetic hair' | 'hair bundles' | 'accessories'>;
}

/**
 * Item in *Catalog → Colors*
 */
export interface CatalogDocumentDataColorsItem {
	/**
	 * Color field in *Catalog → Colors*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.colors[].color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<'gold' | 'silver'>;
}

/**
 * Item in *Catalog → Sizes*
 */
export interface CatalogDocumentDataSizesItem {
	/**
	 * Size field in *Catalog → Sizes*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.sizes[].size
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	size: prismic.SelectField<'14 inches' | '16 inches' | '22 inches'>;
}

type CatalogDocumentDataSlicesSlice = never;

/**
 * Content for Catalog documents
 */
interface CatalogDocumentData {
	/**
	 * Title field in *Catalog*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Categories field in *Catalog*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.categories[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	categories: prismic.GroupField<Simplify<CatalogDocumentDataCategoriesItem>>;

	/**
	 * Colors field in *Catalog*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.colors[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	colors: prismic.GroupField<Simplify<CatalogDocumentDataColorsItem>>;

	/**
	 * Sizes field in *Catalog*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.sizes[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sizes: prismic.GroupField<Simplify<CatalogDocumentDataSizesItem>>;

	/**
	 * MaxPrice field in *Catalog*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.maxprice
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	maxprice: prismic.NumberField;

	/**
	 * Slice Zone field in *Catalog*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<CatalogDocumentDataSlicesSlice> /**
	 * Meta Title field in *Catalog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: catalog.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Catalog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: catalog.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Catalog*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: catalog.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Catalog document from Prismic
 *
 * - **API ID**: `catalog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CatalogDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CatalogDocumentData>,
	'catalog',
	Lang
>;

/**
 * Item in *Categories → Categories*
 */
export interface CategoriesDocumentDataCategoriesItem {
	/**
	 * Category field in *Categories → Categories*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.categories[].category
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	category: prismic.SelectField<'human hair' | 'synthetic hair' | 'hair bundles' | 'accessories'>;
}

/**
 * Item in *Categories → Colors*
 */
export interface CategoriesDocumentDataColorsItem {
	/**
	 * color field in *Categories → Colors*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.colors[].color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<'gold' | 'silver'>;
}

/**
 * Item in *Categories → Sizes*
 */
export interface CategoriesDocumentDataSizesItem {
	/**
	 * size field in *Categories → Sizes*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.sizes[].size
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	size: prismic.SelectField<'14 inches' | '16 inches'>;
}

/**
 * Content for Categories documents
 */
interface CategoriesDocumentData {
	/**
	 * Categories field in *Categories*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.categories[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	categories: prismic.GroupField<Simplify<CategoriesDocumentDataCategoriesItem>>;

	/**
	 * Colors field in *Categories*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.colors[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	colors: prismic.GroupField<Simplify<CategoriesDocumentDataColorsItem>>;

	/**
	 * Sizes field in *Categories*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.sizes[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sizes: prismic.GroupField<Simplify<CategoriesDocumentDataSizesItem>>;
}

/**
 * Categories document from Prismic
 *
 * - **API ID**: `categories`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<CategoriesDocumentData>,
	'categories',
	Lang
>;

/**
 * Item in *Filters → Categories*
 */
export interface FiltersDocumentDataCategoriesItem {
	/**
	 * Category field in *Filters → Categories*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: filters.categories[].category
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	category: prismic.SelectField<'human hair' | 'synthetic hair' | 'hair bundles' | 'accessories'>;
}

/**
 * Item in *Filters → Colors*
 */
export interface FiltersDocumentDataColorsItem {
	/**
	 * Color field in *Filters → Colors*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: filters.colors[].color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<'gold' | 'silver'>;
}

/**
 * Item in *Filters → Sizes*
 */
export interface FiltersDocumentDataSizesItem {
	/**
	 * Size field in *Filters → Sizes*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: filters.sizes[].size
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	size: prismic.SelectField<'14 inches' | '16 inches' | '22 inches'>;
}

/**
 * Content for Filters documents
 */
interface FiltersDocumentData {
	/**
	 * Categories field in *Filters*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: filters.categories[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	categories: prismic.GroupField<Simplify<FiltersDocumentDataCategoriesItem>>;

	/**
	 * Colors field in *Filters*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: filters.colors[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	colors: prismic.GroupField<Simplify<FiltersDocumentDataColorsItem>>;

	/**
	 * Sizes field in *Filters*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: filters.sizes[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sizes: prismic.GroupField<Simplify<FiltersDocumentDataSizesItem>>;

	/**
	 * MaxPrice field in *Filters*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: filters.maxprice
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	maxprice: prismic.NumberField;
}

/**
 * Filters document from Prismic
 *
 * - **API ID**: `filters`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FiltersDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FiltersDocumentData>,
	'filters',
	Lang
>;

type PageDocumentDataSlicesSlice = ProductfloorSlice | AboutSlice | HeroSlice | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

type PolicyDocumentDataSlicesSlice = never;

/**
 * Content for Policy documents
 */
interface PolicyDocumentData {
	/**
	 * Title field in *Policy*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: policy.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Body field in *Policy*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: policy.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Slice Zone field in *Policy*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: policy.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PolicyDocumentDataSlicesSlice> /**
	 * Meta Title field in *Policy*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: policy.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Policy*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: policy.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Policy*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: policy.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Policy document from Prismic
 *
 * - **API ID**: `policy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PolicyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PolicyDocumentData>,
	'policy',
	Lang
>;

/**
 * Item in *Product → Colors*
 */
export interface ProductDocumentDataColorsItem {
	/**
	 * Color field in *Product → Colors*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.colors[].color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<'gold' | 'silver' | 'pink'>;
}

/**
 * Item in *Product → Sizes*
 */
export interface ProductDocumentDataSizesItem {
	/**
	 * Size field in *Product → Sizes*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.sizes[].size
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	size: prismic.KeyTextField;
}

/**
 * Item in *Product → Images*
 */
export interface ProductDocumentDataImagesItem {
	/**
	 * Image field in *Product → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item in *Product → Policies*
 */
export interface ProductDocumentDataPoliciesItem {
	/**
	 * Policy field in *Product → Policies*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.policies[].policy
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	policy: prismic.ContentRelationshipField<'policy'>;
}

type ProductDocumentDataSlicesSlice = DetailSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
	/**
	 * Name field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Description field in *Product*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Category field in *Product*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	category: prismic.SelectField<'human hair' | 'synthetic hair' | 'hair bundles' | 'accessories'>;

	/**
	 * Price field in *Product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;

	/**
	 * Discount field in *Product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.discount
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	discount: prismic.NumberField;

	/**
	 * Colors field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.colors[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	colors: prismic.GroupField<Simplify<ProductDocumentDataColorsItem>>;

	/**
	 * Sizes field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.sizes[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sizes: prismic.GroupField<Simplify<ProductDocumentDataSizesItem>>;

	/**
	 * Search Metadata field in *Product*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.search_metadata
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	search_metadata: prismic.RichTextField;

	/**
	 * Details field in *Product*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.details
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	details: prismic.RichTextField;

	/**
	 * Images field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<ProductDocumentDataImagesItem>>;

	/**
	 * Video field in *Product*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.video
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video: prismic.EmbedField;

	/**
	 * Policies field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.policies[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	policies: prismic.GroupField<Simplify<ProductDocumentDataPoliciesItem>>;

	/**
	 * Slice Zone field in *Product*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
	 * Meta Title field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: product.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: product.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProductDocumentData>,
	'product',
	Lang
>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
	/**
	 * Link field in *Settings → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Label field in *Settings → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
}

type SettingsDocumentDataSlicesSlice = PoliciesSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Site Title field in *Settings*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	site_title: prismic.RichTextField;

	/**
	 * Meta Description field in *Settings*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	meta_description: prismic.RichTextField;

	/**
	 * OG Image field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.og_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;

	/**
	 * Navigation field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

	/**
	 * Slice Zone field in *Settings*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

export type AllDocumentTypes =
	| CatalogDocument
	| CategoriesDocument
	| FiltersDocument
	| PageDocument
	| PolicyDocument
	| ProductDocument
	| SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
	/**
	 * Title field in *About → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * body field in *About → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * CTA Link field in *About → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * CTA Label field in *About → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_label: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AboutSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<'about', AboutSliceVariation>;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
	/**
	 * Title field in *Banner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Subline field in *Banner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.subline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subline: prismic.RichTextField;

	/**
	 * Image field in *Banner → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BannerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<'banner', BannerSliceVariation>;

/**
 * Item in *Detail → Default → Primary → Lengths*
 */
export interface DetailSliceDefaultPrimaryLengthsItem {
	/**
	 * length field in *Detail → Default → Primary → Lengths*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.lengths[].length
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	length: prismic.KeyTextField;
}

/**
 * Item in *Detail → Default → Primary → Images*
 */
export interface DetailSliceDefaultPrimaryImagesItem {
	/**
	 * Image field in *Detail → Default → Primary → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item in *Detail → Default → Primary → Colors*
 */
export interface DetailSliceDefaultPrimaryColorsItem {
	/**
	 * Color field in *Detail → Default → Primary → Colors*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.colors[].color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	color: prismic.ColorField;
}

/**
 * Primary content in *Detail → Default → Primary*
 */
export interface DetailSliceDefaultPrimary {
	/**
	 * Name field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.TitleField;

	/**
	 * Description field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Price field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.price
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;

	/**
	 * Discount field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.discount
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	discount: prismic.NumberField;

	/**
	 * Lengths field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.lengths[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	lengths: prismic.GroupField<Simplify<DetailSliceDefaultPrimaryLengthsItem>>;

	/**
	 * Images field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<DetailSliceDefaultPrimaryImagesItem>>;

	/**
	 * Quantity field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.quantity
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	quantity: prismic.NumberField;

	/**
	 * Colors field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.colors[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	colors: prismic.GroupField<Simplify<DetailSliceDefaultPrimaryColorsItem>>;

	/**
	 * Category field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.category
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	category: prismic.SelectField<'Human Hair' | 'Synthetic Hair' | 'Hair Bundles' | 'Accessories'>;

	/**
	 * Details field in *Detail → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: detail.default.primary.details
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	details: prismic.RichTextField;
}

/**
 * Default variation for Detail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<DetailSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Detail*
 */
type DetailSliceVariation = DetailSliceDefault;

/**
 * Detail Shared Slice
 *
 * - **API ID**: `detail`
 * - **Description**: Detail
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailSlice = prismic.SharedSlice<'detail', DetailSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Sliders*
 */
export interface HeroSliceDefaultPrimarySlidersItem {
	/**
	 * Title field in *Hero → Default → Primary → Sliders*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Subline field in *Hero → Default → Primary → Sliders*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[].subline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subline: prismic.RichTextField;

	/**
	 * Image field in *Hero → Default → Primary → Sliders*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Color field in *Hero → Default → Primary → Sliders*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[].color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	color: prismic.ColorField;

	/**
	 * Font Color field in *Hero → Default → Primary → Sliders*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[].font_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	font_color: prismic.ColorField;

	/**
	 * CTA Label field in *Hero → Default → Primary → Sliders*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[].cta_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_label: prismic.KeyTextField;

	/**
	 * CTA Link field in *Hero → Default → Primary → Sliders*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[].cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Sliders field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.sliders[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sliders: prismic.GroupField<Simplify<HeroSliceDefaultPrimarySlidersItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *Policies → Default → Primary*
 */
export interface PoliciesSliceDefaultPrimary {
	/**
	 * Return Policy field in *Policies → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: policies.default.primary.return_policy
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	return_policy: prismic.RichTextField;

	/**
	 * Shipping Policy field in *Policies → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: policies.default.primary.shipping_policy
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	shipping_policy: prismic.RichTextField;
}

/**
 * Default variation for Policies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PoliciesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PoliciesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Policies*
 */
type PoliciesSliceVariation = PoliciesSliceDefault;

/**
 * Policies Shared Slice
 *
 * - **API ID**: `policies`
 * - **Description**: Policies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PoliciesSlice = prismic.SharedSlice<'policies', PoliciesSliceVariation>;

/**
 * Item in *Productfloor → Default → Primary → Products*
 */
export interface ProductfloorSliceDefaultPrimaryProductsItem {
	/**
	 * Product field in *Productfloor → Default → Primary → Products*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: productfloor.default.primary.products[].product
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	product: prismic.ContentRelationshipField;
}

/**
 * Primary content in *Productfloor → Default → Primary*
 */
export interface ProductfloorSliceDefaultPrimary {
	/**
	 * Title field in *Productfloor → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: productfloor.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * USP field in *Productfloor → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: productfloor.default.primary.usp
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	usp: prismic.RichTextField;

	/**
	 * CTA field in *Productfloor → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: productfloor.default.primary.cta
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta: prismic.LinkField;

	/**
	 * Products field in *Productfloor → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: productfloor.default.primary.products[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	products: prismic.GroupField<Simplify<ProductfloorSliceDefaultPrimaryProductsItem>>;
}

/**
 * Default variation for Productfloor Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductfloorSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProductfloorSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Productfloor*
 */
type ProductfloorSliceVariation = ProductfloorSliceDefault;

/**
 * Productfloor Shared Slice
 *
 * - **API ID**: `productfloor`
 * - **Description**: Productfloor
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductfloorSlice = prismic.SharedSlice<'productfloor', ProductfloorSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			CatalogDocument,
			CatalogDocumentData,
			CatalogDocumentDataCategoriesItem,
			CatalogDocumentDataColorsItem,
			CatalogDocumentDataSizesItem,
			CatalogDocumentDataSlicesSlice,
			CategoriesDocument,
			CategoriesDocumentData,
			CategoriesDocumentDataCategoriesItem,
			CategoriesDocumentDataColorsItem,
			CategoriesDocumentDataSizesItem,
			FiltersDocument,
			FiltersDocumentData,
			FiltersDocumentDataCategoriesItem,
			FiltersDocumentDataColorsItem,
			FiltersDocumentDataSizesItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			PolicyDocument,
			PolicyDocumentData,
			PolicyDocumentDataSlicesSlice,
			ProductDocument,
			ProductDocumentData,
			ProductDocumentDataColorsItem,
			ProductDocumentDataSizesItem,
			ProductDocumentDataImagesItem,
			ProductDocumentDataPoliciesItem,
			ProductDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataNavigationItem,
			SettingsDocumentDataSlicesSlice,
			AllDocumentTypes,
			AboutSlice,
			AboutSliceDefaultPrimary,
			AboutSliceVariation,
			AboutSliceDefault,
			BannerSlice,
			BannerSliceDefaultPrimary,
			BannerSliceVariation,
			BannerSliceDefault,
			DetailSlice,
			DetailSliceDefaultPrimaryLengthsItem,
			DetailSliceDefaultPrimaryImagesItem,
			DetailSliceDefaultPrimaryColorsItem,
			DetailSliceDefaultPrimary,
			DetailSliceVariation,
			DetailSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimarySlidersItem,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			PoliciesSlice,
			PoliciesSliceDefaultPrimary,
			PoliciesSliceVariation,
			PoliciesSliceDefault,
			ProductfloorSlice,
			ProductfloorSliceDefaultPrimaryProductsItem,
			ProductfloorSliceDefaultPrimary,
			ProductfloorSliceVariation,
			ProductfloorSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault
		};
	}
}
